kind = "web"
previewPath = "/"
title = "Smart File Manager"
version = "1.0.0"
id = "artifacts/file-manager"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19703

[services.development]
run = "pnpm --filter @workspace/file-manager run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/file-manager", "run", "build" ]
publicDir = "artifacts/file-manager/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19703"
BASE_PATH = "/"
